<div id="users-login" class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="panel">
		  	<div class="panel-heading">
		  		<p class="panel-title"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Login</p>
		 	</div>
		  	<div class="panel-body">
				<form role="form" method="post">
			  		<div class="form-group">
			    		<label for="exampleInputEmail1"><?php echo $this->form->name->getLabel() ?></label>
			    		<?php echo $this->form->name ?>
			  		</div>
			  		<div class="form-group">
			    		<label for="exampleInputPassword1"><?php echo $this->form->password->getLabel() ?></label>
			    		<?php echo $this->form->password ?>
			  		</div>
					<?php echo $this->partial('_partials/messenger.phtml', array('flashMessenger' => $this->flashMessenger)) ?>
		  			<button type="submit" class="btn btn-primary">Login</button>
				</form>
		  	</div>
		</div>
	</div>
	<div class="col-md-4"></div>
</div>