<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="deleteModalLabel">Löschen bestätigen</h4>
      </div>
      <div class="modal-body">
        Sind Sie sicher dass Sie den Eintrag entfernen wollen?
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Nein</a>
        <a class="btn btn-primary-own" href="#">Ja</a>
      </div>
    </div>
  </div>
</div>