<div class="modal fade" id="sendModal" tabindex="-1" role="dialog" aria-labelledby="sendModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="sendModalLabel">Passwort eingeben und Zugangsdaten senden</h4>
      </div>
      <form method="POST" action="<?php echo $this->url(array('controller' => 'Users', 'action' => 'send-password'), null, true) ?>">
	      <div class="modal-body">
	      		<div class="form-group">
	      			<label>Neues Passwort eingeben:</label>
	    			<input class="form-control" type="text" name="pwNew">
	      		</div>
	      </div>
	      <div class="modal-footer">
	        	<a class="btn btn-default" data-dismiss="modal">Abbrechen</a>
	        	<input type="hidden" value="" name="id" />
	      		<button class="btn btn-primary-own" type="submit">Senden</button>
	      </div>
      </form>
    </div>
  </div>
</div>